import React,{useEffect,useState}from"react";
import{SafeAreaView,View,Text,TextInput,TouchableOpacity,ScrollView,StyleSheet,Alert}from"react-native";
import AsyncStorage from"@react-native-async-storage/async-storage";
const API="http://localhost:5000/api/v1";
async function req(path,opt={},token=""){const r=await fetch(API+path,{...opt,headers:{"Content-Type":"application/json",...(token?{Authorization:"Bearer "+token}:{})}});const j=await r.json();if(!r.ok)throw Error(j.error||"Request failed");return j}
export default function App(){
 const[token,setToken]=useState(null),[screen,setScreen]=useState("Home"),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[data,setData]=useState(null);
 useEffect(()=>{AsyncStorage.getItem("token").then(setToken)},[]);
 useEffect(()=>{if(token)load("dashboard")},[token]);
 async function login(){try{const j=await req("/auth/login",{method:"POST",body:JSON.stringify({email,password})});await AsyncStorage.setItem("token",j.access_token);setToken(j.access_token)}catch(e){Alert.alert("Sign in failed",e.message)}}
 async function load(type){const map={Home:"/dashboard",Courses:"/me/enrollments",Assignments:"/me/enrollments",Attendance:"/me/attendance",Results:"/me/transcript",Timetable:"/me/timetable",Events:"/events",Clubs:"/clubs",Documents:"/documents",Services:"/service-requests",Fees:"/fees",Messages:"/messages"};try{let j=await req(map[type]||map.Home,{},token);if(type==="Assignments"){let a=[];for(const x of j.items){const q=await req("/offerings/"+x.offering_id+"/assignments",{},token);a.push(...q.items)}j={items:a}}setData(j);setScreen(type)}catch(e){Alert.alert("Error",e.message)}}
 if(!token)return <SafeAreaView style={s.safe}><View style={s.login}><Text style={s.logo}>CampusHub</Text><Text style={s.muted}>University management + community</Text><TextInput style={s.input} placeholder="Email" value={email} onChangeText={setEmail}/><TextInput style={s.input} placeholder="Password" secureTextEntry value={password} onChangeText={setPassword}/><TouchableOpacity style={s.btn} onPress={login}><Text style={s.btnText}>Sign in</Text></TouchableOpacity></View></SafeAreaView>;
 const items=data?.items||[];
 return <SafeAreaView style={s.safe}><View style={s.header}><Text style={s.title}>{screen}</Text><TouchableOpacity onPress={()=>load(screen)}><Text>↻</Text></TouchableOpacity></View><ScrollView style={s.body}>{screen==="Home"&&<View><View style={s.grid}><Card t="Courses" v={data?.stats?.courses||0}/><Card t="Assignments" v={data?.stats?.upcoming_assignments||0}/><Card t="Attendance" v={(data?.stats?.attendance_percent||0)+"%"}/></View><Text style={s.h2}>Upcoming work</Text></View>}{screen==="Results"&&<View style={s.card}><Text style={s.h2}>CGPA {data?.cgpa??0}</Text><Text>Credits: {data?.credits??0}</Text></View>}{items.map((x,i)=><View style={s.row} key={i}><Text style={s.rowTitle}>{x.title||x.name||x.request_type||x.body||("Item "+(x.id||i+1))}</Text><Text style={s.muted}>{x.status||x.category||x.event_type||""}</Text></View>)}</ScrollView><ScrollView horizontal style={s.tabs}>{["Home","Courses","Assignments","Attendance","Results","Timetable","Events","Clubs","Documents","Services","Fees","Messages"].map(x=><TouchableOpacity key={x} style={s.tab} onPress={()=>load(x)}><Text>{x}</Text></TouchableOpacity>)}</ScrollView></SafeAreaView>}
function Card({t,v}){return <View style={s.card}><Text style={s.muted}>{t}</Text><Text style={s.stat}>{v}</Text></View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#f5f7fb"},header:{padding:18,flexDirection:"row",justifyContent:"space-between",backgroundColor:"#fff"},title:{fontSize:24,fontWeight:"800"},body:{padding:16},login:{margin:25,padding:22,backgroundColor:"#fff",borderRadius:18},logo:{fontSize:30,fontWeight:"800"},muted:{color:"#64748b"},input:{borderWidth:1,borderColor:"#cbd5e1",borderRadius:10,padding:12,marginTop:12},btn:{backgroundColor:"#2563eb",padding:13,borderRadius:10,marginTop:14},btnText:{color:"#fff",textAlign:"center",fontWeight:"700"},grid:{flexDirection:"row",flexWrap:"wrap",gap:10},card:{backgroundColor:"#fff",padding:18,borderRadius:14,marginBottom:12,minWidth:140},stat:{fontSize:28,fontWeight:"800",marginTop:5},h2:{fontSize:20,fontWeight:"800",marginVertical:16},row:{backgroundColor:"#fff",padding:15,borderRadius:12,marginBottom:9},rowTitle:{fontWeight:"700"},tabs:{maxHeight:58,backgroundColor:"#fff",padding:8},tab:{padding:12}});
