import React,{useEffect,useState}from"react";
import{SafeAreaView,View,Text,TextInput,TouchableOpacity,ScrollView,StyleSheet,Alert,Linking}from"react-native";
import AsyncStorage from"@react-native-async-storage/async-storage";

const API=process.env.EXPO_PUBLIC_API_URL||"http://localhost:5000/api/v1";
async function req(path,opt={},token=""){
 const r=await fetch(API+path,{...opt,headers:{"Content-Type":"application/json",...(token?{Authorization:"Bearer "+token}:{})}});
 const j=await r.json().catch(()=>({}));
 if(!r.ok)throw Error(j.error||j.message||"Request failed");
 return j;
}
const adminTabs=[["Overview","overview"],["Institution","institution"],["Members","members"],["Departments","departments"],["Sessions","sessions"],["Groups","groups"],["Requests","requests"],["Faculties","faculties"],["Programs","programs"],["Courses","adminCourses"],["Events","adminEvents"],["Clubs","adminClubs"],["Services","adminServices"],["Fees","adminFees"]];
const userTabs=["Home","Courses","Course Registration","Assignments","Attendance","Results","Timetable","Calendar","Announcements","Community","Events","Clubs","Documents","Services","Certificates","Campus","Library","Hostel","Lost & Found","Fees","Messages","Search"];

export default function App(){
 const[token,setToken]=useState(null),[screen,setScreen]=useState("Home"),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[fullName,setFullName]=useState(""),[username,setUsername]=useState(""),[registerMode,setRegisterMode]=useState(false),[data,setData]=useState(null),[admins,setAdmins]=useState([]),[institution,setInstitution]=useState(null),[form,setForm]=useState({});
 useEffect(()=>{AsyncStorage.getItem("token").then(setToken)},[]);
 useEffect(()=>{if(token){req("/my/institutions",{},token).then(j=>{const first=(j.items||[])[0];if(first)setInstitution(first)}).catch(()=>{});load("Home")}},[token]);
 async function login(){try{const j=await req("/auth/login",{method:"POST",body:JSON.stringify({email,password})});await AsyncStorage.setItem("token",j.access_token);setToken(j.access_token)}catch(e){Alert.alert("Sign in failed",e.message)}}
 async function register(){try{if(!fullName||!username||!email||password.length<8)return Alert.alert("Create account","Enter name, username, email and a password of at least 8 characters.");const j=await req("/auth/register",{method:"POST",body:JSON.stringify({full_name:fullName,username,email,password})});const l=await req("/auth/login",{method:"POST",body:JSON.stringify({email,password})});await AsyncStorage.setItem("token",l.access_token);setToken(l.access_token);setRegisterMode(false);Alert.alert("Account created","Your CampusHub account is ready.")}catch(e){Alert.alert("Registration failed",e.message)}}
 async function load(type,iid=institution?.id){
  const map={Home:"/dashboard",Courses:"/me/enrollments","Course Registration":"/me/course-registration",Assignments:"/me/enrollments",Attendance:"/me/attendance",Results:"/me/transcript",Timetable:"/me/timetable",Calendar:"/academic-calendar",Announcements:"/institutions/"+(iid||0)+"/announcements",Community:"/groups/"+(iid||0)+"/feed",Events:"/events",Clubs:"/clubs",Documents:"/documents",Services:"/service-requests",Certificates:"/certificates",Campus:"/campus-services",Library:"/library/"+(iid||0)+"/items",Hostel:"/hostel/"+(iid||0)+"/rooms","Lost & Found":"/lost-found",Fees:"/fees",Messages:"/messages",Search:"/search/all?q=student"};
  try{
   if(type==="Admin"){const j=await req("/admin/institutions",{},token);setAdmins(j.items||[]);if((j.items||[]).length){setInstitution(j.items[0]);setScreen("Overview");await loadAdmin("overview",j.items[0].id)}else{setScreen("Admin");setData({items:[]})}return}
   if(adminTabs.some(x=>x[0]===type)){if(!iid)return Alert.alert("University Admin","No institution is assigned to your account.");await loadAdmin(type,iid);return}
   let j=await req(map[type]||map.Home,{},token);
   if(type==="Assignments"){let a=[];for(const x of j.items||[]){const q=await req("/offerings/"+x.offering_id+"/assignments",{},token);a.push(...(q.items||[]))}j={items:a}}
   setData(j);setScreen(type);
  }catch(e){Alert.alert("Error",e.message)}
 }
 async function loadAdmin(type,iid){
  const path={overview:"/admin/overview",institution:"/admin",members:"/admin/members",departments:"/admin/departments",sessions:"/admin/sessions",groups:"/admin/groups",requests:"/admin/requests",faculties:"/admin/faculties",programs:"/admin/programs",adminCourses:"/admin/courses",adminEvents:"/admin/events",adminClubs:"/admin/clubs",adminServices:"/admin/service-requests",adminFees:"/admin/fees"}[type];
  try{const j=await req("/institutions/"+iid+path,{},token);setData(j);setScreen(type);if(j.institution)setInstitution(j.institution)}catch(e){Alert.alert("Admin error",e.message)}
 }
 function setField(k,v){setForm(x=>({...x,[k]:v}))}
 async function saveInstitution(){
  try{const j=await req("/institutions/"+institution.id+"/admin/institution",{method:"PUT",body:JSON.stringify(form)},token);setInstitution(j.data);setData(x=>({...x,institution:j.data}));setForm({});Alert.alert("Saved","Institution details updated.");}
  catch(e){Alert.alert("Could not save",e.message)}
 }
 async function mutate(path,method,body,success="Saved"){
  try{await req(path,{method,body:JSON.stringify(body)},token);Alert.alert("Success",success);await load(screen,institution.id)}catch(e){Alert.alert("Admin error",e.message)}
 }
 if(!token)return <SafeAreaView style={s.safe}><View style={s.login}><Text style={s.logo}>CampusHub</Text><Text style={s.muted}>{registerMode?"Create your university account":"University management + community"}</Text>{registerMode&&<><TextInput style={s.input} placeholder="Full name" value={fullName} onChangeText={setFullName}/><TextInput style={s.input} placeholder="Username" value={username} onChangeText={setUsername}/></>}<TextInput style={s.input} placeholder="Email" value={email} onChangeText={setEmail} autoCapitalize="none"/><TextInput style={s.input} placeholder="Password" secureTextEntry value={password} onChangeText={setPassword}/><TouchableOpacity style={s.btn} onPress={registerMode?register:login}><Text style={s.btnText}>{registerMode?"Create account":"Sign in"}</Text></TouchableOpacity><TouchableOpacity onPress={()=>setRegisterMode(!registerMode)}><Text style={s.link}>{registerMode?"Already have an account? Sign in":"Create a new account"}</Text></TouchableOpacity></View></SafeAreaView>;

 const items=data?.items||[];
 return <SafeAreaView style={s.safe}>
  <View style={s.header}><View><Text style={s.title}>{screen}</Text>{institution&&adminTabs.some(x=>x[0]===screen)&&<Text style={s.muted}>{institution.name} · {data?.role||"admin"}</Text>}</View><TouchableOpacity onPress={()=>load(screen)}><Text style={s.refresh}>↻</Text></TouchableOpacity></View>
  {screen==="Overview"&&<ScrollView style={s.body}><Text style={s.h2}>{institution?.name}</Text><View style={s.grid}>{Object.entries(data?.counts||{}).map(([k,v])=><Card key={k} t={k.replaceAll("_"," ")} v={v}/>)}</View><Text style={s.h2}>Permissions</Text><Text style={s.muted}>{(data?.permissions||[]).join(" · ")}</Text></ScrollView>}
  {screen==="Institution"&&<ScrollView style={s.body}><Text style={s.h2}>Edit university</Text><Field label="Name" value={form.name??institution?.name??""} onChangeText={v=>setField("name",v)}/><Field label="Slug" value={form.slug??institution?.slug??""} onChangeText={v=>setField("slug",v)}/><Field label="Type" value={form.kind??institution?.kind??""} onChangeText={v=>setField("kind",v)}/><Field label="Address" value={form.address??institution?.address??""} onChangeText={v=>setField("address",v)}/><Field label="Website" value={form.website??institution?.website??""} onChangeText={v=>setField("website",v)}/><Field label="Description" value={form.description??institution?.description??""} onChangeText={v=>setField("description",v)}/><TouchableOpacity style={s.btn} onPress={saveInstitution}><Text style={s.btnText}>Save institution</Text></TouchableOpacity></ScrollView>}
  {screen!=="Overview"&&screen!=="Institution"&&<ScrollView style={s.body}>{items.map((x,i)=><AdminRow key={i} x={x} screen={screen} iid={institution?.id} token={token} reload={()=>load(screen,institution?.id)} mutate={mutate}/>)}</ScrollView>}
  {screen==="Home"&&<View style={s.body}><View style={s.grid}><Card t="Courses" v={data?.stats?.courses||0}/><Card t="Assignments" v={data?.stats?.upcoming_assignments||0}/><Card t="Attendance" v={(data?.stats?.attendance_percent||0)+"%"}/></View><Text style={s.h2}>University Admin</Text><TouchableOpacity style={s.adminBtn} onPress={()=>load("Admin")}><Text style={s.adminText}>Open creator / admin panel</Text></TouchableOpacity></View>}
  {screen!=="Home"&&screen!=="Overview"&&screen!=="Institution"&&!adminTabs.some(x=>x[0]===screen)&&<ScrollView style={s.body}>{screen==="Results"&&<View style={s.card}><Text style={s.h2}>CGPA {data?.cgpa??0}</Text><Text>Credits: {data?.credits??0}</Text><TouchableOpacity style={s.btn} onPress={()=>Linking.openURL(API+"/transcript.pdf")}><Text style={s.btnText}>Open transcript PDF</Text></TouchableOpacity><TouchableOpacity style={s.btn} onPress={()=>Linking.openURL(API+"/me/id-card.pdf")}><Text style={s.btnText}>Open student ID card</Text></TouchableOpacity></View>}{screen==="Community"&&<View style={s.card}><Text style={s.h2}>Community feed</Text><Text style={s.muted}>Open a group from the web admin or group list to see posts, comments, reactions and polls.</Text></View>}{screen==="Search"&&<View style={s.card}><Text style={s.h2}>Global search</Text><Text style={s.muted}>Search is available across university users, courses, departments and institutions.</Text></View>}{items.map((x,i)=><View style={s.row} key={i}><Text style={s.rowTitle}>{x.title||x.name||x.request_type||x.body||("Item "+(x.id||i+1))}</Text><Text style={s.muted}>{x.status||x.category||x.event_type||x.kind||""}</Text></View>)}</ScrollView>}
  <ScrollView horizontal style={s.tabs}>{userTabs.map(x=><TouchableOpacity key={x} style={s.tab} onPress={()=>load(x)}><Text>{x}</Text></TouchableOpacity>)}<TouchableOpacity style={s.tab} onPress={()=>load("Admin")}><Text>University Admin</Text></TouchableOpacity></ScrollView>
  {adminTabs.some(x=>x[0]===screen)&&<ScrollView horizontal style={s.adminTabs}>{adminTabs.map(([label,key])=><TouchableOpacity key={label} style={s.tab} onPress={()=>load(label,institution?.id)}><Text>{label}</Text></TouchableOpacity>)}</ScrollView>}
  {admins.length>1&&screen!=="Home"&&<ScrollView horizontal style={s.adminTabs}>{admins.map(a=><TouchableOpacity key={a.id} style={s.tab} onPress={()=>{setInstitution(a);setScreen("Overview");loadAdmin("overview",a.id)}}><Text>{a.name}</Text></TouchableOpacity>)}</ScrollView>}
 </SafeAreaView>
}
function AdminRow({x,screen,iid,mutate,reload}){
 const[editing,setEditing]=useState(false),[name,setName]=useState(x.name||x.title||x.full_name||""),[status,setStatus]=useState(x.status||"");
 const editMap={Members:"members",Departments:"departments",Groups:"groups",Faculties:"faculties",Programs:"programs",adminCourses:"courses",adminEvents:"events",adminClubs:"clubs",adminServices:"service-requests",adminFees:"fees"};
 const endpoint=editMap[screen]; const id=x.id||x.membership_id;
 const canEdit=["Members","Departments","Groups","Faculties","Programs","adminCourses","adminEvents","adminClubs","adminServices","adminFees"].includes(screen);
 if(editing)return <View style={s.row}><TextInput style={s.input} value={name} onChangeText={setName}/><TextInput style={s.input} value={status} onChangeText={setStatus} placeholder="Status"/><View style={s.actions}><TouchableOpacity style={s.smallBtn} onPress={()=>{const body=screen==="adminServices"?{status}:screen==="adminFees"?{title:name}:screen==="Members"?{role:status}:screen==="Departments"?{name,code:x.code}:screen==="adminEvents"?{title:name}:screen==="adminClubs"?{name}:screen==="Groups"?{name}:screen==="Faculties"?{name}:screen==="Programs"?{name}:screen==="adminCourses"?{title:name}:{name};mutate("/institutions/"+iid+"/admin/"+endpoint+"/"+id,"PUT",body);setEditing(false)}}><Text style={s.btnText}>Save</Text></TouchableOpacity><TouchableOpacity onPress={()=>setEditing(false)}><Text>Cancel</Text></TouchableOpacity></View></View>
 return <View style={s.row}><Text style={s.rowTitle}>{name||x.email||("ID "+id)}</Text><Text style={s.muted}>{x.role||x.code||x.department_name||x.status||x.event_type||""}</Text>{canEdit&&<TouchableOpacity style={s.smallBtn} onPress={()=>setEditing(true)}><Text style={s.btnText}>Edit</Text></TouchableOpacity>}{screen==="Requests"&&x.status==="pending"&&<View style={s.actions}><TouchableOpacity style={s.smallBtn} onPress={()=>mutate("/institutions/"+iid+"/admin/requests/"+x.id+"/review","POST",{decision:"approve"},"Request approved")}><Text style={s.btnText}>Approve</Text></TouchableOpacity><TouchableOpacity style={s.dangerBtn} onPress={()=>mutate("/institutions/"+iid+"/admin/requests/"+x.id+"/review","POST",{decision:"reject"},"Request rejected")}><Text style={s.btnText}>Reject</Text></TouchableOpacity></View>}</View>
}
function Field({label,...p}){return <View><Text style={s.label}>{label}</Text><TextInput style={s.input} {...p}/></View>}
function Card({t,v}){return <View style={s.card}><Text style={s.muted}>{t}</Text><Text style={s.stat}>{v}</Text></View>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:"#f5f7fb"},header:{padding:18,flexDirection:"row",justifyContent:"space-between",backgroundColor:"#fff"},title:{fontSize:24,fontWeight:"800"},refresh:{fontSize:24},body:{padding:16},login:{margin:25,padding:22,backgroundColor:"#fff",borderRadius:18},logo:{fontSize:30,fontWeight:"800"},muted:{color:"#64748b"},label:{fontWeight:"700",marginTop:12},link:{color:"#2563eb",textAlign:"center",marginTop:14},input:{borderWidth:1,borderColor:"#cbd5e1",borderRadius:10,padding:12,marginTop:6,backgroundColor:"#fff"},btn:{backgroundColor:"#2563eb",padding:13,borderRadius:10,marginTop:14},adminBtn:{backgroundColor:"#0f172a",padding:16,borderRadius:12},btnText:{color:"#fff",textAlign:"center",fontWeight:"700"},adminText:{color:"#fff",fontWeight:"700",textAlign:"center"},grid:{flexDirection:"row",flexWrap:"wrap",gap:10},card:{backgroundColor:"#fff",padding:18,borderRadius:14,marginBottom:12,minWidth:140},stat:{fontSize:28,fontWeight:"800",marginTop:5},h2:{fontSize:20,fontWeight:"800",marginVertical:16},row:{backgroundColor:"#fff",padding:15,borderRadius:12,marginBottom:9},rowTitle:{fontWeight:"700",marginBottom:5},tabs:{maxHeight:58,backgroundColor:"#fff",padding:8},adminTabs:{maxHeight:55,backgroundColor:"#e2e8f0"},tab:{padding:12},actions:{flexDirection:"row",gap:8,marginTop:8},smallBtn:{backgroundColor:"#2563eb",padding:9,borderRadius:8,marginTop:8},dangerBtn:{backgroundColor:"#dc2626",padding:9,borderRadius:8,marginTop:8}});
