from django.urls import path
from .views import healthz,register,login,me,logout,logout_all,institutions,my_institutions,join_institution,profile,create_institution,verification_request,verification_confirm,password_reset_request,password_reset_confirm
from .academic_views import faculties,programs,courses,offerings,enroll,my_enrollments,attendance,my_attendance,assignments,submit_assignment,grade_submission,exams,results,transcript,student_results,timetable,my_timetable,semester_results,course_registration,academic_summary,assignment_mine,offering_submissions
from .life_views import events,register_event,clubs,join_club,documents,service_requests,fees,fee_detail,messages,read_message,user_profile,search,dashboard,notifications,notification_read,change_password,announcements,event_ticket,checkin,certificate,certificates,campus_services,lost_found,emergency_contacts,bus_routes,hostel,library_items,my_loans,borrow,return_loan,cafeteria,materials,add_material,academic_calendar,advanced_request,advanced_requests,register_push,unregister_push,verification,confirm_verification,announcement_read
from .community_views import institution_groups,groups,join_group,posts,comment,feed,reaction,attachments,polls,vote
from .pdf_views import id_card,transcript_pdf
from .admin_views import overview,institution_admin,members,invite,departments,sessions,years,admin_groups,requests,permissions,faculties as admin_faculties,admin_programs,admin_courses,admin_events,admin_clubs,admin_service_requests,admin_fees

urlpatterns=[
 path("auth/register",register),path("me/id-card.pdf",id_card),path("transcript.pdf",transcript_pdf),path("auth/login",login),path("auth/me",me),path("auth/logout",logout),path("auth/logout-all",logout_all),path("auth/change-password",change_password),path("auth/verification/request",verification_request),path("auth/verification/confirm",verification_confirm),path("auth/password-reset/request",password_reset_request),path("auth/password-reset/confirm",password_reset_confirm),
 path("institutions",institutions),path("institutions/create",create_institution),path("my/institutions",my_institutions),path("institutions/<int:iid>/join",join_institution),path("profile",profile),
 path("institutions/<int:iid>/faculties",faculties),path("departments/<int:did>/programs",programs),path("departments/<int:did>/courses",courses),path("courses/<int:cid>/offerings",offerings),
 path("offerings/<int:oid>/enroll",enroll),path("me/enrollments",my_enrollments),path("offerings/<int:oid>/attendance",attendance),path("me/attendance",my_attendance),
 path("offerings/<int:oid>/assignments",assignments),path("assignments/<int:aid>/submit",submit_assignment),path("submissions/<int:sid>/grade",grade_submission),
 path("offerings/<int:oid>/exams",exams),path("me/results",results),path("students/<int:sid>/results",student_results),path("me/transcript",transcript),
 path("offerings/<int:oid>/timetable",timetable),path("me/timetable",my_timetable),path("results/semester/<int:semester_id>",semester_results),path("me/course-registration",course_registration),path("me/academic-summary",academic_summary),
 path("assignments/<int:aid>/mine",assignment_mine),path("offerings/<int:oid>/submissions",offering_submissions),path("offerings/<int:oid>/materials",materials),path("offerings/<int:oid>/materials/add",add_material),
 path("groups",groups),path("institutions/<int:iid>/groups",institution_groups),path("groups/<int:gid>/join",join_group),path("groups/<int:gid>/posts",posts),path("groups/<int:gid>/feed",feed),
 path("posts/<int:pid>/comments",comment),path("posts/<int:pid>/reactions",reaction),path("posts/<int:pid>/attachments",attachments),path("groups/<int:gid>/polls",polls),path("polls/<int:pid>/vote",vote),
 path("messages",messages),path("messages/<int:mid>/read",read_message),path("users/<int:uid>/profile",user_profile),path("search",search),path("search/all",search),path("dashboard",dashboard),
 path("notifications",notifications),path("notifications/<int:nid>/read",notification_read),path("institutions/<int:iid>/announcements",announcements),path("announcements/<int:aid>/read",announcement_read),
 path("events",events),path("events/<int:eid>/register",register_event),path("events/<int:eid>/ticket",event_ticket),path("events/tickets/<str:code>/check-in",checkin),path("events/<int:eid>/certificate",certificate),path("certificates",certificates),
 path("clubs",clubs),path("clubs/<int:cid>/join",join_club),path("documents",documents),path("service-requests",service_requests),path("service-requests/advanced",advanced_request),path("service-requests/advanced/list",advanced_requests),
 path("fees",fees),path("fees/<int:fid>",fee_detail),path("campus-services",campus_services),path("institutions/<int:iid>/campus-services",campus_services),path("lost-found",lost_found),path("institutions/<int:iid>/lost-found",lost_found),
 path("emergency-contacts/<int:iid>",emergency_contacts),path("bus-routes/<int:iid>",bus_routes),path("hostel/<int:iid>/rooms",hostel),path("hostel/<int:iid>/apply",hostel),path("library/<int:iid>/items",library_items),path("library/my-loans",my_loans),path("library/items/<int:item_id>/borrow",borrow),path("library/loans/<int:lid>/return",return_loan),path("cafeteria/<int:iid>",cafeteria),
 path("push/devices",register_push),path("push/devices/unregister",unregister_push),path("profile/verification",verification),path("profile/verification/confirm",confirm_verification),path("academic-calendar/<int:iid>",academic_calendar),
 path("institutions/<int:iid>/admin/overview",overview),path("institutions/<int:iid>/admin/institution",institution_admin),path("institutions/<int:iid>/admin/members",members),path("institutions/<int:iid>/admin/members/<int:uid>",members),path("institutions/<int:iid>/admin/members/invite",invite),
 path("institutions/<int:iid>/admin/departments",departments),path("institutions/<int:iid>/admin/sessions",sessions),path("institutions/<int:iid>/admin/years",years),path("institutions/<int:iid>/admin/groups",admin_groups),path("institutions/<int:iid>/admin/requests",requests),path("institutions/<int:iid>/admin/permissions",permissions),
 path("institutions/<int:iid>/admin/faculties",admin_faculties),path("institutions/<int:iid>/admin/programs",admin_programs),path("institutions/<int:iid>/admin/courses",admin_courses),path("institutions/<int:iid>/admin/events",admin_events),path("institutions/<int:iid>/admin/clubs",admin_clubs),path("institutions/<int:iid>/admin/service-requests",admin_service_requests),path("institutions/<int:iid>/admin/fees",admin_fees),
]