const API=window.CAMPUSHUB_API||"/api/v1";let token=localStorage.getItem("campushub_token"),page="dashboard",me=null;
const $=s=>document.querySelector(s);
async function api(path,opt={}){const r=await fetch(API+path,{...opt,headers:{"Content-Type":"application/json",...(token?{Authorization:"Bearer "+token}:{}),...(opt.headers||{})}});const j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||"Request failed");return j}
async function boot(){if(token){try{me=await api("/auth/me")}catch{token=null;localStorage.removeItem("campushub_token")}}render()}
function render(){if(!token){login();return}document.querySelector("#app").innerHTML='<div class="shell"><aside class="side"><div class="brand">CampusHub</div><div class="nav">'+["dashboard","courses","assignments","attendance","results","timetable","events","clubs","documents","services","fees","messages"].map(p=>'<button class="'+(page===p?"active":"")+'" onclick="go(\''+p+'\')">'+p[0].toUpperCase()+p.slice(1)+'</button>').join("")+'<button onclick="logout()">Sign out</button></div></aside><main class="main"><div class="top"><div><h1>'+page[0].toUpperCase()+page.slice(1)+'</h1><div class="muted">'+(me?.profile?.full_name||"Campus member")+'</div></div><button class="btn" onclick="load()">Refresh</button></div><section id="content"></section></main></div>';load()}
function login(){document.querySelector("#app").innerHTML='<div class="form card"><h1>CampusHub</h1><p class="muted">University management + community.</p><input id="email" placeholder="Email"><input id="password" type="password" placeholder="Password"><button class="btn" onclick="doLogin()">Sign in</button></div>'}
async function doLogin(){try{const j=await api("/auth/login",{method:"POST",body:JSON.stringify({email:$("#email").value,password:$("#password").value})});token=j.access_token;localStorage.setItem("campushub_token",token);await boot()}catch(e){alert(e.message)}}
function logout(){token=null;localStorage.removeItem("campushub_token");render()}function go(p){page=p;render()}const card=(a,b)=>'<div class="card"><div class="muted">'+a+'</div><div class="stat">'+b+'</div></div>';
async function load(){const c=$("#content");try{if(page==="dashboard"){const j=await api("/dashboard").catch(()=>({stats:{courses:0,upcoming_assignments:0,attendance_percent:0}}));c.innerHTML='<div class="grid">'+card("Courses",j.stats.courses)+card("Upcoming assignments",j.stats.upcoming_assignments)+card("Attendance",j.stats.attendance_percent+"%")+card("Notifications",j.stats.unread_notifications||0)+'</div>'}else if(page==="courses"){const j=await api("/me/enrollments");c.innerHTML='<div class="list">'+j.items.map(x=>'<div class="row"><b>Offering #'+x.offering_id+'</b><span>'+x.status+'</span></div>').join("")+'</div>'}else if(page==="assignments"){const e=await api("/me/enrollments");let a=[];for(const x of e.items){const j=await api("/offerings/"+x.offering_id+"/assignments");a.push(...j.items)}c.innerHTML='<div class="list">'+a.map(x=>'<div class="card"><h3>'+x.title+'</h3><p>'+x.description+'</p><span class="muted">Due: '+(x.due_at||"—")+'</span></div>').join("")+'</div>'}else if(page==="attendance"){const j=await api("/me/attendance");c.innerHTML='<div class="list">'+j.items.map(x=>'<div class="row"><b>'+x.date+'</b><span>'+x.status+'</span></div>').join("")+'</div>'}else if(page==="results"){const j=await api("/me/transcript");c.innerHTML='<div class="grid">'+card("CGPA",j.cgpa)+card("Credits",j.credits)+'</div><div class="list">'+j.results.map(x=>'<div class="row"><b>Course #'+x.course_id+'</b><span>'+x.grade+' · '+x.grade_point+'</span></div>').join("")+'</div>'}else if(page==="timetable"){const j=await api("/me/timetable");c.innerHTML='<div class="list">'+j.items.map(x=>'<div class="row"><b>Offering #'+x.offering_id+'</b><span>Day '+x.weekday+' · '+x.start_time+'–'+x.end_time+' · '+x.room+'</span></div>').join("")+'</div>'}else{const paths={events:"/events",clubs:"/clubs",documents:"/documents",services:"/service-requests",fees:"/fees",messages:"/messages"};const j=await api(paths[page]||"/events");c.innerHTML='<div class="list">'+(j.items||[]).map(x=>'<div class="row"><b>'+(x.title||x.name||x.request_type||x.body||("Item #"+x.id))+'</b><span>'+(x.status||x.category||x.event_type||"")+'</span></div>').join("")+'</div>'}}catch(e){c.innerHTML='<div class="card"><h2>Unable to load</h2><p>'+e.message+'</p></div>'}}
boot();