const API=window.CAMPUSHUB_API||"/api/v1";
let token=localStorage.getItem("campushub_token"),page="dashboard",me=null,adminInstitutions=[],adminId=null,adminPage="overview",authView="landing";
const $=s=>document.querySelector(s);
const esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]));
async function api(path,opt={}){const r=await fetch(API+path,{...opt,headers:{"Content-Type":"application/json",...(token?{Authorization:"Bearer "+token}:{}),...(opt.headers||{})}});const j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||"Request failed");return j}
async function boot(){if(token){try{me=await api("/auth/me");adminInstitutions=(await api("/admin/institutions")).items||[];adminId=adminId||adminInstitutions[0]?.id}catch{token=null;localStorage.removeItem("campushub_token")}}render()}
function nav(){const base=["dashboard","courses","assignments","attendance","results","timetable","events","clubs","documents","services","fees","messages"];return base.map(p=>'<button class="'+(page===p?"active":"")+'" onclick="go(\''+p+'\')">'+p[0].toUpperCase()+p.slice(1)+'</button>').join("")+(adminInstitutions.length?'<button class="'+(page==="admin"?"active":"")+'" onclick="go(\'admin\')">University Admin</button>':"")}
function render(){if(!token){publicHome();return}document.querySelector("#app").innerHTML='<div class="shell"><aside class="side"><div class="brand">CampusHub</div><div class="nav">'+nav()+'<button onclick="logout()">Sign out</button></div></aside><main class="main"><div class="top"><div><h1>'+esc(page==="admin"?"University Admin":page[0].toUpperCase()+page.slice(1))+'</h1><div class="muted">'+esc(me?.profile?.full_name||"Campus member")+'</div></div><button class="btn" onclick="load()">Refresh</button></div><section id="content"></section></main></div>';load()}
function publicHome(){if(authView==="login"){login();return}if(authView==="register"){registerView();return}if(authView==="profile"){profileSetup();return}if(authView==="choose"){chooseInstitution();return}landing()}
function login(){document.querySelector("#app").innerHTML='<div class="auth-page"><div class="auth-card"><div class="brand dark">CampusHub</div><h1>Welcome back</h1><p class="muted">Sign in to your university community.</p><input id="email" type="email" placeholder="Email"><input id="password" type="password" placeholder="Password" onkeydown="if(event.key===\'Enter\')doLogin()"><button class="btn wide" onclick="doLogin()">Sign in</button><div class="auth-links"><button onclick="authView=\'register\';render()">Create account</button><button onclick="authView=\'landing\';render()">Back to CampusHub</button></div></div></div>'}
function landing(){document.querySelector("#app").innerHTML='<div class="landing"><header class="landing-nav"><div class="brand">CampusHub</div><div><button class="ghost" onclick="authView=\'login\';render()">Sign in</button><button class="btn" onclick="authView=\'register\';render()">Create account</button></div></header><section class="hero"><div><span class="eyebrow">UNIVERSITY • COMMUNITY • CONNECTION</span><h1>Everything your university needs, in one place.</h1><p>Manage academics, attendance, results, events, clubs, services, fees and student communities from one secure campus platform.</p><div class="hero-actions"><button class="btn big" onclick="authView=\'register\';render()">Join CampusHub</button><button class="ghost big" onclick="authView=\'login\';render()">I already have an account</button></div></div><div class="hero-panel"><div class="hero-icon">CH</div><h3>One campus. One community.</h3><p class="muted">Students, teachers and university administrators can work together through a single responsive platform.</p></div></section><section class="features"><div class="feature"><b>Academic hub</b><span>Courses, assignments, attendance, results and timetables.</span></div><div class="feature"><b>Campus life</b><span>Events, clubs, documents, services and community groups.</span></div><div class="feature"><b>University administration</b><span>Manage members, departments, programs, courses, fees and requests.</span></div><div class="feature"><b>Mobile ready</b><span>Use the same account across the web and mobile app.</span></div></section><section class="public-section"><div><span class="eyebrow">OPEN UNIVERSITIES</span><h2>Find your university</h2><p class="muted">Choose your institution after creating your account, or ask your university administrator for an invitation.</p></div><div id="publicInstitutions" class="institution-grid"><div class="card">Loading universities…</div></div></section><footer>CampusHub · University management + community platform</footer></div>';loadPublicInstitutions()}
async function loadPublicInstitutions(){try{const j=await api("/institutions");const el=$("#publicInstitutions");if(!j.items?.length){el.innerHTML='<div class="card"><b>No universities published yet.</b><p class="muted">Create an account to get started.</p></div>';return}el.innerHTML=j.items.map(i=>'<div class="institution-card"><div class="inst-mark">'+esc((i.name||"U").slice(0,1).toUpperCase())+'</div><div><h3>'+esc(i.name)+'</h3><p class="muted">'+esc(i.kind||"University")+(i.address?" · "+esc(i.address):"")+'</p></div><button class="btn" onclick="authView=\'register\';render()">Join</button></div>').join("")}catch(e){$("#publicInstitutions").innerHTML='<div class="card"><p class="muted">Universities will appear here when they are published.</p></div>'}}
function registerView(){document.querySelector("#app").innerHTML='<div class="auth-page"><div class="auth-card wide-card"><div class="brand dark">CampusHub</div><h1>Create your account</h1><p class="muted">Start your university profile. You can join an institution after setup.</p><div class="two"><input id="regName" placeholder="Full name"><input id="regUsername" placeholder="Username"></div><input id="regEmail" type="email" placeholder="Email"><div class="two"><input id="regPassword" type="password" placeholder="Password (8+ characters)"><input id="regPassword2" type="password" placeholder="Confirm password"></div><button class="btn wide" onclick="doRegister()">Create account</button><div class="auth-links"><button onclick="authView=\'login\';render()">Already have an account? Sign in</button><button onclick="authView=\'landing\';render()">Back</button></div></div></div>'}
async function doRegister(){const name=$("#regName").value.trim(),username=$("#regUsername").value.trim(),email=$("#regEmail").value.trim(),password=$("#regPassword").value,password2=$("#regPassword2").value;if(password!==password2){alert("Passwords do not match");return}if(password.length<8){alert("Password must be at least 8 characters");return}try{await api("/auth/register",{method:"POST",body:JSON.stringify({full_name:name,username,email,password})});const j=await api("/auth/login",{method:"POST",body:JSON.stringify({email,password})});token=j.access_token;localStorage.setItem("campushub_token",token);await boot();authView="profile";render()}catch(e){alert(e.message)}}
function profileSetup(){document.querySelector("#app").innerHTML='<div class="auth-page"><div class="auth-card wide-card"><div class="brand dark">CampusHub</div><h1>Complete your profile</h1><p class="muted">A few details are needed before you can join or create a university.</p><div class="two"><input id="pPhone" placeholder="Phone"><input id="pStudent" placeholder="Student ID"></div><div class="two"><input id="pAddress" placeholder="Address"><input id="pInstitution" placeholder="Institution name (optional)"></div><div class="two"><input id="pDepartment" placeholder="Department"><input id="pProgram" placeholder="Program / degree"></div><textarea id="pBio" placeholder="Short bio (optional)"></textarea><button class="btn wide" onclick="saveProfile()">Save profile & continue</button><button class="ghost wide" onclick="skipProfile()">Complete this later</button></div></div>'}
async function saveProfile(){try{await api("/profile",{method:"PUT",body:JSON.stringify({phone:$("#pPhone").value,address:$("#pAddress").value,student_id:$("#pStudent").value,institution_text:$("#pInstitution").value,department:$("#pDepartment").value,program:$("#pProgram").value,bio:$("#pBio").value})});authView="choose";render()}catch(e){alert(e.message)}}
function skipProfile(){authView="landing";render()}function chooseInstitution(){document.querySelector("#app").innerHTML='<div class="auth-page"><div class="auth-card wide-card"><div class="brand dark">CampusHub</div><h1>Choose your university</h1><p class="muted">Join an existing university or create one for your institution.</p><div id="chooseList" class="institution-grid"><div class="card">Loading universities…</div></div><div class="divider">or</div><button class="btn wide" onclick="createUniversityForm()">Create a university</button><button class="ghost wide" onclick="authView=\'landing\';render()">Skip for now</button></div></div>';loadChooseInstitutions()}
async function loadChooseInstitutions(){try{const j=await api("/institutions");const el=$("#chooseList");if(!j.items?.length){el.innerHTML='<div class="card"><b>No universities yet.</b><p class="muted">You can create the first one.</p></div>';return}el.innerHTML=j.items.map(i=>'<div class="institution-card"><div class="inst-mark">'+esc((i.name||"U").slice(0,1).toUpperCase())+'</div><div><h3>'+esc(i.name)+'</h3><p class="muted">'+esc(i.kind||"University")+'</p></div><button class="btn" onclick="joinUniversity('+i.id+')">Join</button></div>').join("")}catch(e){alert(e.message)}}
async function joinUniversity(iid){try{const institutions=await api("/institutions");const inst=institutions.items.find(x=>x.id===iid);const name=inst?.name||"this university";const d=await api("/institutions/"+iid+"/departments");if(!d.items?.length){alert("This university has not published departments yet. Contact its administrator.");return}const choice=prompt("Enter department number:\n"+d.items.map((x,n)=>(n+1)+". "+x.name+" ("+x.code+")").join("\n"));const dep=d.items[Number(choice)-1];if(!dep){alert("Invalid department");return}const student_id=prompt("Student ID",me?.profile?.student_id||"");const program=prompt("Program / degree",me?.profile?.program||"");const session=prompt("Session (for example 2026-27)","2026-27");const academic_year=prompt("Academic year (for example Year 1)","Year 1");if(!student_id||!program||!session||!academic_year)return;await api("/institutions/"+iid+"/join",{method:"POST",body:JSON.stringify({department_id:dep.id,student_id,program,session,academic_year})});alert("Join request submitted to "+name+". You can sign in while it is reviewed.");authView="landing";render()}catch(e){alert(e.message)}}
function createUniversityForm(){document.querySelector("#app").innerHTML='<div class="auth-page"><div class="auth-card wide-card"><div class="brand dark">CampusHub</div><h1>Create your university</h1><p class="muted">You will become the institution owner and can manage it from University Admin.</p><input id="uName" placeholder="University name"><input id="uSlug" placeholder="Slug, e.g. my-university"><input id="uKind" placeholder="Type" value="university"><input id="uAddress" placeholder="Address"><input id="uWebsite" placeholder="Website"><textarea id="uDescription" placeholder="Description"></textarea><button class="btn wide" onclick="createUniversity()">Create university</button><button class="ghost wide" onclick="authView=\'choose\';render()">Back</button></div></div>'}
async function createUniversity(){try{const d={name:$("#uName").value.trim(),slug:$("#uSlug").value.trim().toLowerCase(),kind:$("#uKind").value.trim()||"university",address:$("#uAddress").value.trim(),website:$("#uWebsite").value.trim(),description:$("#uDescription").value.trim()};if(!d.name||!d.slug){alert("University name and slug are required");return}const j=await api("/institutions",{method:"POST",body:JSON.stringify(d)});alert("University created. You are now the institution owner.");await boot();page="admin";adminId=j.id;render()}catch(e){alert(e.message)}}
async function doLogin(){try{const j=await api("/auth/login",{method:"POST",body:JSON.stringify({email:$("#email").value,password:$("#password").value})});token=j.access_token;localStorage.setItem("campushub_token",token);await boot()}catch(e){alert(e.message)}}
function logout(){token=null;localStorage.removeItem("campushub_token");render()}function go(p){page=p;render()}
const card=(a,b)=>'<div class="card"><div class="muted">'+esc(a)+'</div><div class="stat">'+esc(b)+'</div></div>';
const list=items=>'<div class="list">'+items.map(x=>'<div class="row"><b>'+esc(x.title||x.name||x.full_name||x.email||("Item #"+x.id))+'</b><span>'+esc(x.status||x.role||x.code||"")+'</span></div>').join("")+'</div>';
async function load(){const c=$("#content");try{
if(page==="admin"){await loadAdmin(c);return}
if(page==="dashboard"){const j=await api("/dashboard").catch(()=>({stats:{courses:0,upcoming_assignments:0,attendance_percent:0}}));c.innerHTML='<div class="grid">'+card("Courses",j.stats.courses)+card("Upcoming assignments",j.stats.upcoming_assignments)+card("Attendance",j.stats.attendance_percent+"%")+card("Notifications",j.stats.unread_notifications||0)+'</div>';return}
if(page==="courses"){c.innerHTML=list((await api("/me/enrollments")).items);return}
if(page==="assignments"){const e=await api("/me/enrollments"),a=[];for(const x of e.items)a.push(...(await api("/offerings/"+x.offering_id+"/assignments")).items);c.innerHTML=list(a);return}
if(page==="attendance"){c.innerHTML=list((await api("/me/attendance")).items);return}
if(page==="results"){const j=await api("/me/transcript");c.innerHTML='<div class="grid">'+card("CGPA",j.cgpa)+card("Credits",j.credits)+'</div>'+list(j.results);return}
if(page==="timetable"){c.innerHTML=list((await api("/me/timetable")).items);return}
const paths={events:"/events",clubs:"/clubs",documents:"/documents",services:"/service-requests",fees:"/fees",messages:"/messages"};c.innerHTML=list((await api(paths[page]||"/events")).items||[]);
}catch(e){c.innerHTML='<div class="card"><h2>Unable to load</h2><p>'+esc(e.message)+'</p></div>'}}
async function loadAdmin(c){
if(!adminId){c.innerHTML='<div class="card"><h2>No managed university</h2><p>Create a university or ask an owner to grant you an admin role.</p></div>';return}
const tabs=["overview","institution","members","departments","sessions","faculties","programs","courses","groups","requests","events","clubs","services","fees"];
c.innerHTML='<div class="admin-head"><select id="adminUni" onchange="adminId=Number(this.value);adminPage=\'overview\';loadAdmin(document.querySelector(\'#content\'))">'+adminInstitutions.map(i=>'<option value="'+i.id+'" '+(i.id===adminId?"selected":"")+'>'+esc(i.name)+' · '+esc(i.role)+'</option>').join("")+'</select><div class="tabs">'+tabs.map(t=>'<button class="'+(adminPage===t?"active":"")+'" onclick="adminPage=\''+t+'\';loadAdmin(document.querySelector(\'#content\'))">'+t+'</button>').join("")+'</div></div><div id="adminBody"></div>';
const b=$("#adminBody");const q="/institutions/"+adminId+"/admin/";
if(adminPage==="overview"){const j=await api(q+"overview");b.innerHTML='<div class="grid">'+Object.entries(j.counts).map(([k,v])=>card(k,v)).join("")+'</div><div class="card"><h2>Role: '+esc(j.role)+'</h2><p class="muted">Your role controls exactly which university records you can edit.</p></div>';return}
if(adminPage==="institution"){const j=await api(q+"");const i=j.institution;b.innerHTML='<div class="form card"><h2>Edit university</h2>'+["name","slug","kind","address","website","description"].map(k=>'<input id="i_'+k+'" placeholder="'+k+'" value="'+esc(i[k])+'">').join("")+'<button class="btn" onclick="saveInstitution()">Save changes</button></div>';return}
if(adminPage==="members"){const j=await api(q+"members");b.innerHTML='<div class="form card"><h2>Add existing user</h2><input id="inviteEmail" placeholder="User email"><select id="inviteRole">'+["student","teacher","department_admin","media_manager","class_representative","principal","institution_admin"].map(x=>'<option>'+x+'</option>').join("")+'</select><input id="inviteStudent" placeholder="Student ID (optional)"><button class="btn" onclick="inviteUser()">Add member</button></div>'+j.items.map(x=>'<div class="row card"><div><b>'+esc(x.full_name||x.email)+'</b><div class="muted">'+esc(x.email)+' · '+esc(x.student_id||"")+'</div></div><select onchange="changeRole('+x.id+',this.value)">'+["student","teacher","department_admin","media_manager","class_representative","principal","institution_admin","institution_owner"].map(r=>'<option '+(x.role===r?"selected":"")+'>'+r+'</option>').join("")+'</select><button onclick="suspendMember('+x.id+')">Suspend</button></div>').join("");return}
const loaders={departments:"departments",sessions:"sessions",faculties:"faculties",programs:"programs",courses:"courses",groups:"groups",requests:"requests",events:"events",clubs:"clubs",services:"service-requests",fees:"fees"};
if(loaders[adminPage]){const j=await api(q+loaders[adminPage]);b.innerHTML=adminEditor(adminPage,j.items||[]);return}
}
function adminEditor(type,items){
let form="";
if(type==="departments")form='<input id="aName" placeholder="Department name"><input id="aCode" placeholder="Code"><button class="btn" onclick="addDepartment()">Add department</button>';
if(type==="sessions")form='<input id="aDep" placeholder="Department ID"><input id="aName" placeholder="Session name"><button class="btn" onclick="addSession()">Add session</button><input id="aSession" placeholder="Session ID"><input id="aYear" placeholder="Academic year name"><button class="btn" onclick="addYear()">Add year</button>';
if(type==="faculties")form='<input id="aName" placeholder="Faculty name"><input id="aCode" placeholder="Code"><button class="btn" onclick="addFaculty()">Add faculty</button>';
if(type==="programs")form='<input id="aDep" placeholder="Department ID"><input id="aName" placeholder="Program name"><input id="aCode" placeholder="Code"><input id="aDegree" placeholder="Degree"><button class="btn" onclick="addProgram()">Add program</button>';
if(type==="courses")form='<input id="aDep" placeholder="Department ID"><input id="aCode" placeholder="Course code"><input id="aName" placeholder="Course title"><input id="aCredits" placeholder="Credits" value="3"><button class="btn" onclick="addCourse()">Add course</button>';
if(type==="groups")form='<input id="aName" placeholder="Group name"><input id="aType" placeholder="Type" value="community"><input id="aDesc" placeholder="Description"><button class="btn" onclick="addGroup()">Create group</button>';
if(type==="events")form='<input id="aName" placeholder="Event title"><input id="aDesc" placeholder="Description"><input id="aLocation" placeholder="Location"><button class="btn" onclick="addEvent()">Create event</button>';
if(type==="fees")form='<input id="aStudent" placeholder="Student user ID"><input id="aName" placeholder="Fee title"><input id="aAmount" placeholder="Amount"><button class="btn" onclick="addFee()">Create fee</button>';
if(type==="requests")return items.map(x=>'<div class="row card"><span>Request #'+x.id+' · user '+x.user_id+' · '+esc(x.program)+'</span><span><button onclick="reviewRequest('+x.id+',\'approve\')">Approve</button> <button onclick="reviewRequest('+x.id+',\'reject\')">Reject</button></span></div>').join("");
if(type==="services")return items.map(x=>'<div class="row card"><span>#'+x.id+' · '+esc(x.request_type)+' · '+esc(x.details)+'</span><button onclick="serviceUpdate('+x.id+')">'+esc(x.status)+'</button></div>').join("");
return '<div class="form card">'+form+'</div>'+list(items);
}
async function postAdmin(path,body){await api("/institutions/"+adminId+"/admin/"+path,{method:"POST",body:JSON.stringify(body)});await loadAdmin($("#content"))}
async function saveInstitution(){const d={};["name","slug","kind","address","website","description"].forEach(k=>d[k]=$("#i_"+k).value);await api("/institutions/"+adminId+"/admin/institution",{method:"PUT",body:JSON.stringify(d)});alert("Saved");await boot()}
async function inviteUser(){await postAdmin("members/invite",{email:$("#inviteEmail").value,role:$("#inviteRole").value,student_id:$("#inviteStudent").value})}
async function changeRole(id,role){await api("/institutions/"+adminId+"/admin/members/"+id,{method:"PUT",body:JSON.stringify({role})});}
async function suspendMember(id){await api("/institutions/"+adminId+"/admin/members/"+id,{method:"DELETE"});await loadAdmin($("#content"))}
async function addDepartment(){await postAdmin("departments",{name:$("#aName").value,code:$("#aCode").value})}
async function addSession(){await postAdmin("sessions",{department_id:Number($("#aDep").value),name:$("#aName").value})}
async function addYear(){await postAdmin("years",{session_id:Number($("#aSession").value),name:$("#aYear").value})}
async function addFaculty(){await postAdmin("faculties",{name:$("#aName").value,code:$("#aCode").value})}
async function addProgram(){await postAdmin("programs",{department_id:Number($("#aDep").value),name:$("#aName").value,code:$("#aCode").value,degree:$("#aDegree").value})}
async function addCourse(){await postAdmin("courses",{department_id:Number($("#aDep").value),code:$("#aCode").value,title:$("#aName").value,credits:Number($("#aCredits").value)})}
async function addGroup(){await postAdmin("groups",{name:$("#aName").value,group_type:$("#aType").value,description:$("#aDesc").value})}
async function addEvent(){await postAdmin("events",{title:$("#aName").value,description:$("#aDesc").value,location:$("#aLocation").value})}
async function addFee(){await postAdmin("fees",{student_id:Number($("#aStudent").value),title:$("#aName").value,amount:Number($("#aAmount").value)})}
async function reviewRequest(id,decision){await api("/institutions/"+adminId+"/admin/requests/"+id+"/review",{method:"POST",body:JSON.stringify({decision})});await loadAdmin($("#content"))}
async function serviceUpdate(id){const status=prompt("New status: submitted, processing, completed, rejected");if(!status)return;const response=prompt("Response (optional)")||"";await api("/institutions/"+adminId+"/admin/service-requests/"+id,{method:"PUT",body:JSON.stringify({status,response})});await loadAdmin($("#content"))}
boot();